### ISSUE TITLE
Crash app lors d'un delete avec id bidon

### ISSUE THREAD

**Issue by SonofaPancak** [Avantage-Numerique/bdsol-api#12]
Lorsqu'une requête /personnes/delete, dont data:{ id } est bidon est envoyée, l'api crash. pour cause (errorsObj.name) :

> bdsolapi  | [LOG]["Delete Personne route for ",{"id":"bidon"}]
bdsolapi  | [LOG]["Début de la suppression d'une personne"]
bdsolapi  | /api/src/Http/Responses/ErrorResponse.ts:25
bdsolapi  |                     name: errorsObj.name,
bdsolapi  |                                     ^
bdsolapi  | TypeError: Cannot read properties of undefined (reading 'name')
bdsolapi  |     at Function.create (/api/src/Http/Responses/ErrorResponse.ts:25:37)
bdsolapi  |     at PersonnesService.<anonymous> (/api/src/Database/Service.ts:169:34)
bdsolapi  |     at Generator.throw (<anonymous>)
bdsolapi  |     at rejected (/api/src/Database/Service.ts:29:65)
bdsolapi  |     at runMicrotasks (<anonymous>)
bdsolapi  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

dans " api/src/Database/service.ts " la fonctione " async delete " dans le catch :
`return ErrorResponse.create(
                deleteError.errors,
                StatusCodes.INTERNAL_SERVER_ERROR,
                deleteError.message || "Error on delete item in Service"
            );`
 le premier paramètre "deleteError.errors" ne renvoie pas un ".name"
 
 Piste de solution :
 lorsqu'on remplace "deleteError.errors" par " new Error(" anything ") " ça ne plante plus.

**Comment by SonofaPancak** [comment]
Fixed with issue #11
